insert into users (name, email, password, profilePicture, score, moderator) values ('bbramwell0', 'bcampling0@mediafire.com', '$2a$04$LJX3bXsgpe6uiBbIeua8VOCrc0yNyO8da1nxldqiRM8lMiwwBIheu', 'http://dummyimage.com/228x100.png/dddddd/000000', 2080, false);
insert into users (name, email, password, profilePicture, score, moderator) values ('rbaty1', 'ddrinkhill1@unc.edu', '$2a$04$hgMl3PxYRSZLAx2JFDKJHee2A50kXIzklrKo3r4W9CgCiFthTVAo.', 'http://dummyimage.com/209x100.png/dddddd/000000', 1204, false);
insert into users (name, email, password, profilePicture, score, moderator) values ('dmoberley2', 'bshackel2@java.com', '$2a$04$96wR53STe0mMUSv5SUJVo.Po1mm8Nt8iuC08f4/qfBOYmMWZ2qkVK', 'http://dummyimage.com/126x100.png/ff4444/ffffff', 2044, true);
insert into users (name, email, password, profilePicture, score, moderator) values ('rbaitson3', 'lriddeough3@arstechnica.com', '$2a$04$HxUQmcfEj9NMP.IMAeTfoeYeTh5NiLdL1em.7/RYqA8.nR4Z9PTvS', 'http://dummyimage.com/155x100.png/5fa2dd/ffffff', 3303, false);
insert into users (name, email, password, profilePicture, score, moderator) values ('dtosney4', 'sgrace4@jiathis.com', '$2a$04$7eFAWlYIamTwLLiIDukyI.hUA.obhr7MxIi99Gc5y5tj0kEHJmOFO', 'http://dummyimage.com/198x100.png/dddddd/000000', 583, false);
insert into users (name, email, password, profilePicture, score, moderator) values ('dforde5', 'zedney5@toplist.cz', '$2a$04$4Uo/jTV.oHV5CNTk6eMZi.p36SUdbD4QXjiQpK36rxbWCy9aFBS3W', 'http://dummyimage.com/118x100.png/5fa2dd/ffffff', 2414, false);
insert into users (name, email, password, profilePicture, score, moderator) values ('dnangle6', 'sdirand6@cbc.ca', '$2a$04$yI8Jy6Q7l8KgpGSHFR7pR.oAZUtWWLpVYEvfiy9aG9B1yVOrQaoUG', 'http://dummyimage.com/191x100.png/cc0000/ffffff', 3493, false);
insert into users (name, email, password, profilePicture, score, moderator) values ('aegginton7', 'vcatley7@woothemes.com', '$2a$04$g7vjUyNa5X46vYSlkjCNMuzOU.fMabhZNf91BVGMeqsqirN//hbT6', 'http://dummyimage.com/125x100.png/cc0000/ffffff', 4777, false);
insert into users (name, email, password, profilePicture, score, moderator) values ('apendleberry8', 'jetchingham8@google.fr', '$2a$04$/JRu6HVFxK/egbeHOeOPVO9nWXKsK4t.YJ8mD/hJLdsUgQ1f9VP5W', 'http://dummyimage.com/185x100.png/5fa2dd/ffffff', 1176, true);
insert into users (name, email, password, profilePicture, score, moderator) values ('plapides9', 'rmanford9@uol.com.br', '$2a$04$Qs4dZE..UZb6VLNs9zTQUu1WMXDI3nSJFwBVibI0I7V0dyDmrjb72', 'http://dummyimage.com/183x100.png/5fa2dd/ffffff', 3917, false);
insert into users (name, email, password, profilePicture, score, moderator) values ('dkalewea', 'hmccruddena@cyberchimps.com', '$2a$04$5nS/QvG8bQhxBXCS/RZe7.wZozuadvItcH238tX6lphoxgaLoTd.S', 'http://dummyimage.com/158x100.png/cc0000/ffffff', 4270, false);
insert into users (name, email, password, profilePicture, score, moderator) values ('acecilb', 'cdebullionb@phpbb.com', '$2a$04$Oy0oU2Tg2V7OqN1ab2mupuu6OKADzBF.jo4gYJwFXkEin7W.bPBp.', 'http://dummyimage.com/158x100.png/ff4444/ffffff', 751, true);
insert into users (name, email, password, profilePicture, score, moderator) values ('amarzellac', 'jchealec@goodreads.com', '$2a$04$kz0IitEn1NysdocosgFAIuMbWdoK0ePls5bx9GZA8QYMYxUKv5bea', 'http://dummyimage.com/248x100.png/dddddd/000000', 1870, false);
insert into users (name, email, password, profilePicture, score, moderator) values ('lvynalld', 'lkinsettd@desdev.cn', '$2a$04$vsi7ZfKv6x1VQ86NEOrAYOJveXJwKkctT38LQVGzTcOztWMfMXg12', 'http://dummyimage.com/147x100.png/5fa2dd/ffffff', 1806, false);
insert into users (name, email, password, profilePicture, score, moderator) values ('ijumonte', 'cbrahme@disqus.com', '$2a$04$IyO4K/JtN/7HBcWJPSVCwevkMOJhdpIiU21vrs9Q0a4LtNw.u.pIy', 'http://dummyimage.com/144x100.png/cc0000/ffffff', 3151, false);
insert into users (name, email, password, profilePicture, score, moderator) values ('sespleyf', 'xgossipinf@hao123.com', '$2a$04$v6fQc9CPPUZvVf.vm9o36.3b9OgzT6f06wZk6mShNnIlH3JbpjgWK', 'http://dummyimage.com/110x100.png/cc0000/ffffff', 1095, false);
insert into users (name, email, password, profilePicture, score, moderator) values ('ymellanbyg', 'tpaikeg@wsj.com', '$2a$04$L4JXA5ph1LXkrGc2zxM1wO/9vxaLetOerdobu0c6GF9Vk4jOkL.dm', 'http://dummyimage.com/143x100.png/cc0000/ffffff', 2011, false);
insert into users (name, email, password, profilePicture, score, moderator) values ('nabysh', 'hdewareh@paypal.com', '$2a$04$p6d4s.eHwO6132Kr7bDE/.2m8qGMlZf9J0wGHUs9oqkLg2jUC3AyS', 'http://dummyimage.com/109x100.png/5fa2dd/ffffff', 3921, false);
insert into users (name, email, password, profilePicture, score, moderator) values ('gpascheki', 'ffleotei@fc2.com', '$2a$04$mQESLbNA0pctDCxlQ85Ane.EZFmgVPTid8LURr2FT1VnOkD2Glhtm', 'http://dummyimage.com/115x100.png/ff4444/ffffff', 2267, false);
insert into users (name, email, password, profilePicture, score, moderator) values ('egilliatj', 'mfearneleyj@wordpress.org', '$2a$04$w9o4AH6g2c9WtGf1nbgZL.hrrw2Fb09DNymtegIYMcLPukySjqiR2', 'http://dummyimage.com/174x100.png/dddddd/000000', 1386, true);

insert into admin (email, password) values ('tpetracchi0@mtv.com', '$2a$04$COwP0fZzo1J2mlrrtUy3O.0EK7BI4KbN./sBCpjscBL.B.pOtmf8u');

insert into tag (name, description) values ('sapien in', 'mauris morbi non lectus aliquam sit amet diam');
insert into tag (name, description) values ('donec ut', 'et ultrices posuere cubilia curae nulla dapibus dolor vel est donec');
insert into tag (name, description) values ('quis turpis eget', 'iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis');
insert into tag (name, description) values ('nulla', 'erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis');
insert into tag (name, description) values ('tempus', 'amet consectetuer adipiscing elit proin risus praesent lectus vestibulum quam sapien varius ut');

insert into question (author_id, title, description, timestamp, score) values (-3, 'condimentum id luctus nec', 'turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam', '2023-02-20 01:26:09', 94);
insert into question (author_id, title, description, timestamp, score) values (16, 'lorem integer tincidunt ante vel ipsum', 'pede justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse', '2023-09-15 01:08:08', 130);
insert into question (author_id, title, description, timestamp, score) values (14, 'vestibulum ante ipsum', 'adipiscing elit proin risus praesent lectus vestibulum quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec', '2023-05-07 08:58:17', 47);
insert into question (author_id, title, description, timestamp, score) values (20, 'risus semper porta', 'a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis', '2023-02-13 22:58:31', 81);
insert into question (author_id, title, description, timestamp, score) values (14, 'lacus morbi quis tortor id nulla ultrices', 'et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu', '2023-08-31 14:55:55', 90);
insert into question (author_id, title, description, timestamp, score) values (19, 'magna ac consequat', 'lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique', '2022-12-28 07:22:21', 52);
insert into question (author_id, title, description, timestamp, score) values (14, 'diam cras pellentesque', 'quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut', '2022-12-27 23:54:33', 11);
insert into question (author_id, title, description, timestamp, score) values (3, 'nulla tellus in sagittis dui vel', 'ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam', '2022-12-23 07:59:36', 103);
insert into question (author_id, title, description, timestamp, score) values (17, 'tellus nulla ut erat id mauris', 'praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in', '2022-12-10 10:59:33', 122);
insert into question (author_id, title, description, timestamp, score) values (-15, 'massa quis augue luctus', 'sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis', '2023-01-09 15:20:11', 143);

insert into question_tags (question_id, tag_id) values (5, 3);
insert into question_tags (question_id, tag_id) values (6, 3);
insert into question_tags (question_id, tag_id) values (9, 2);
insert into question_tags (question_id, tag_id) values (7, 5);
insert into question_tags (question_id, tag_id) values (10, 5);
insert into question_tags (question_id, tag_id) values (7, 5);
insert into question_tags (question_id, tag_id) values (9, 2);
insert into question_tags (question_id, tag_id) values (6, 1);
insert into question_tags (question_id, tag_id) values (3, 3);
insert into question_tags (question_id, tag_id) values (7, 2);

insert into answer (author_id, question_id, description, timestamp, score) values (4, 6, 'aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper', '2023-06-27 03:23:28', 15);
insert into answer (author_id, question_id, description, timestamp, score) values (1, 1, 'hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac', '2022-11-21 18:49:39', 11);
insert into answer (author_id, question_id, description, timestamp, score) values (6, 4, 'at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt', '2022-12-11 00:42:49', 42);
insert into answer (author_id, question_id, description, timestamp, score) values (17, 5, 'ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis', '2023-05-07 15:18:33', 40);
insert into answer (author_id, question_id, description, timestamp, score) values (12, 3, 'eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit', '2022-10-30 14:06:04', 11);
insert into answer (author_id, question_id, description, timestamp, score) values (16, 10, 'dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque', '2023-09-20 18:21:49', 32);
insert into answer (author_id, question_id, description, timestamp, score) values (17, 5, 'nulla suspendisse potenti cras in purus eu magna vulputate luctus', '2023-09-11 16:28:52', 48);
insert into answer (author_id, question_id, description, timestamp, score) values (2, 8, 'duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis', '2023-01-30 00:24:27', 12);
insert into answer (author_id, question_id, description, timestamp, score) values (4, 1, 'vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus', '2022-11-29 04:25:12', 14);
insert into answer (author_id, question_id, description, timestamp, score) values (2, 8, 'ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est', '2022-11-06 14:17:06', 12);

insert into comment_question (author_id, question_id, content, timestamp, score) values (5, 9, 'aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed', '2023-06-15 08:02:54', 32);
insert into comment_question (author_id, question_id, content, timestamp, score) values (15, 4, 'proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque', '2023-02-11 05:44:50', 6);
insert into comment_question (author_id, question_id, content, timestamp, score) values (12, 2, 'nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus', '2023-08-20 00:54:59', 25);
insert into comment_question (author_id, question_id, content, timestamp, score) values (8, 5, 'duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in', '2022-11-11 02:37:24', 4);
insert into comment_question (author_id, question_id, content, timestamp, score) values (5, 9, 'non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat', '2023-03-24 03:34:04', 45);
insert into comment_question (author_id, question_id, content, timestamp, score) values (2, 8, 'nullam sit amet turpis elementum ligula vehicula consequat morbi a', '2022-11-24 04:53:58', 28);
insert into comment_question (author_id, question_id, content, timestamp, score) values (1, 3, 'a libero nam dui proin leo odio porttitor id consequat', '2023-04-11 13:10:21', 47);
insert into comment_question (author_id, question_id, content, timestamp, score) values (8, 5, 'vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec', '2023-09-04 18:36:36', 20);
insert into comment_question (author_id, question_id, content, timestamp, score) values (17, 5, 'lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem', '2023-10-09 15:45:20', 44);
insert into comment_question (author_id, question_id, content, timestamp, score) values (6, 6, 'turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet', '2023-04-13 19:18:12', 37);

insert into comment_answer (author_id, answer_id, content, timestamp, score) values (4, 7, 'in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis', '2023-06-18 18:29:55', 15);
insert into comment_answer (author_id, answer_id, content, timestamp, score) values (1, 7, 'sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin', '2023-01-07 13:30:01', 7);
insert into comment_answer (author_id, answer_id, content, timestamp, score) values (13, 8, 'pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla', '2023-09-01 07:19:04', 18);
insert into comment_answer (author_id, answer_id, content, timestamp, score) values (6, 7, 'vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin', '2023-07-05 01:54:14', 7);
insert into comment_answer (author_id, answer_id, content, timestamp, score) values (8, 9, 'blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede', '2023-02-07 14:27:50', 13);
insert into comment_answer (author_id, answer_id, content, timestamp, score) values (15, 1, 'mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget', '2023-01-13 01:25:51', 15);
insert into comment_answer (author_id, answer_id, content, timestamp, score) values (7, 9, 'ultrices vel augue vestibulum ante ipsum primis in faucibus orci', '2023-03-20 23:54:27', 2);
insert into comment_answer (author_id, answer_id, content, timestamp, score) values (12, 6, 'pede justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst', '2023-05-25 12:43:19', 30);
insert into comment_answer (author_id, answer_id, content, timestamp, score) values (8, 6, 'pede justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum', '2023-03-30 06:48:17', 39);
insert into comment_answer (author_id, answer_id, content, timestamp, score) values (5, 1, 'sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien', '2023-09-23 12:22:45', 9);

insert into follow_question (user_id, question_id) values (5, 3);
insert into follow_question (user_id, question_id) values (6, 9);
insert into follow_question (user_id, question_id) values (1, 9);
insert into follow_question (user_id, question_id) values (11, 2);
insert into follow_question (user_id, question_id) values (10, 4);
insert into follow_question (user_id, question_id) values (9, 1);
insert into follow_question (user_id, question_id) values (4, 3);
insert into follow_question (user_id, question_id) values (10, 2);
insert into follow_question (user_id, question_id) values (7, 9);
insert into follow_question (user_id, question_id) values (16, 2);
insert into follow_question (user_id, question_id) values (10, 6);
insert into follow_question (user_id, question_id) values (14, 3);
insert into follow_question (user_id, question_id) values (14, 2);
insert into follow_question (user_id, question_id) values (10, 7);
insert into follow_question (user_id, question_id) values (9, 2);
insert into follow_question (user_id, question_id) values (19, 6);
insert into follow_question (user_id, question_id) values (11, 3);
insert into follow_question (user_id, question_id) values (16, 2);
insert into follow_question (user_id, question_id) values (10, 10);
insert into follow_question (user_id, question_id) values (10, 3);

insert into follow_tag (user_id, tag_id) values (9, 1);
insert into follow_tag (user_id, tag_id) values (13, 2);
insert into follow_tag (user_id, tag_id) values (18, 10);
insert into follow_tag (user_id, tag_id) values (19, 9);
insert into follow_tag (user_id, tag_id) values (17, 10);
insert into follow_tag (user_id, tag_id) values (12, 6);
insert into follow_tag (user_id, tag_id) values (4, 9);
insert into follow_tag (user_id, tag_id) values (18, 3);
insert into follow_tag (user_id, tag_id) values (13, 6);
insert into follow_tag (user_id, tag_id) values (18, 6);
insert into follow_tag (user_id, tag_id) values (5, 4);
insert into follow_tag (user_id, tag_id) values (4, 2);
insert into follow_tag (user_id, tag_id) values (19, 6);
insert into follow_tag (user_id, tag_id) values (15, 4);
insert into follow_tag (user_id, tag_id) values (4, 7);
insert into follow_tag (user_id, tag_id) values (13, 3);
insert into follow_tag (user_id, tag_id) values (3, 7);
insert into follow_tag (user_id, tag_id) values (12, 7);
insert into follow_tag (user_id, tag_id) values (12, 6);
insert into follow_tag (user_id, tag_id) values (11, 5);

insert into follow_user (follower_id, following_id) values (9, 2);
insert into follow_user (follower_id, following_id) values (18, 10);
insert into follow_user (follower_id, following_id) values (5, 6);
insert into follow_user (follower_id, following_id) values (18, 2);
insert into follow_user (follower_id, following_id) values (15, 11);
insert into follow_user (follower_id, following_id) values (4, 16);
insert into follow_user (follower_id, following_id) values (3, 19);
insert into follow_user (follower_id, following_id) values (1, 12);
insert into follow_user (follower_id, following_id) values (4, 8);
insert into follow_user (follower_id, following_id) values (2, 11);
insert into follow_user (follower_id, following_id) values (17, 9);
insert into follow_user (follower_id, following_id) values (6, 8);
insert into follow_user (follower_id, following_id) values (19, 18);
insert into follow_user (follower_id, following_id) values (7, 9);
insert into follow_user (follower_id, following_id) values (7, 15);
insert into follow_user (follower_id, following_id) values (12, 20);
insert into follow_user (follower_id, following_id) values (17, 3);
insert into follow_user (follower_id, following_id) values (3, 18);
insert into follow_user (follower_id, following_id) values (1, 9);
insert into follow_user (follower_id, following_id) values (4, 6);

insert into badge (name, description) values ('definition', 'consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia');
insert into badge (name, description) values ('background', 'lorem ipsum dolor sit amet consectetuer adipiscing elit proin');
insert into badge (name, description) values ('composite', 'elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus');
insert into badge (name, description) values ('methodical', 'elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue');
insert into badge (name, description) values ('open architecture', 'adipiscing elit proin risus praesent lectus vestibulum quam sapien');

insert into user_badges (user_id, badge_id) values (13, 4);
insert into user_badges (user_id, badge_id) values (18, 1);
insert into user_badges (user_id, badge_id) values (5, 2);
insert into user_badges (user_id, badge_id) values (20, 5);
insert into user_badges (user_id, badge_id) values (7, 4);

insert into report_question (question_id, reporter_id, reason, timestamp) values (1, 4, 'primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat', '2023-01-02 18:22:36');
insert into report_question (question_id, reporter_id, reason, timestamp) values (5, 10, 'venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris', '2023-10-15 11:21:54');
insert into report_question (question_id, reporter_id, reason, timestamp) values (3, 5, 'rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia', '2023-07-20 17:57:20');
insert into report_question (question_id, reporter_id, reason, timestamp) values (4, 20, 'et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut', '2023-09-24 13:10:40');
insert into report_question (question_id, reporter_id, reason, timestamp) values (4, 7, 'massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in', '2023-03-30 23:19:27');

insert into report_answer (answer_id, reporter_id, reason, timestamp) values (9, 9, 'erat volutpat in congue etiam justo etiam pretium iaculis justo in hac', '2023-07-07 06:10:26');
insert into report_answer (answer_id, reporter_id, reason, timestamp) values (9, 6, 'blandit nam nulla integer pede justo', '2023-02-25 06:15:19');
insert into report_answer (answer_id, reporter_id, reason, timestamp) values (5, 9, 'odio elementum eu interdum eu tincidunt in leo maecenas pulvinar', '2023-08-30 02:11:26');
insert into report_answer (answer_id, reporter_id, reason, timestamp) values (1, 20, 'in felis donec semper sapien a libero nam dui proin', '2023-07-28 10:51:36');
insert into report_answer (answer_id, reporter_id, reason, timestamp) values (5, 17, 'volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar', '2023-09-12 14:41:23');

insert into report_comment_question (comment_id, reporter_id, reason, timestamp) values (8, 16, 'vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet', '2023-01-13 21:14:18');
insert into report_comment_question (comment_id, reporter_id, reason, timestamp) values (2, 5, 'tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia', '2023-06-14 05:48:56');
insert into report_comment_question (comment_id, reporter_id, reason, timestamp) values (5, 2, 'sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis', '2023-04-29 17:15:30');
insert into report_comment_question (comment_id, reporter_id, reason, timestamp) values (4, 5, 'lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et', '2023-09-03 06:15:04');
insert into report_comment_question (comment_id, reporter_id, reason, timestamp) values (2, 9, 'nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio', '2023-09-28 07:40:03');

insert into report_comment_answer (comment_id, reporter_id, reason, timestamp) values (6, 5, 'auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis', '2023-01-19 10:43:15');
insert into report_comment_answer (comment_id, reporter_id, reason, timestamp) values (5, 4, 'vulputate nonummy maecenas tincidunt lacus at velit vivamus', '2023-06-07 02:43:53');
insert into report_comment_answer (comment_id, reporter_id, reason, timestamp) values (7, 6, 'augue aliquam erat volutpat in congue etiam justo etiam', '2022-12-30 11:02:45');
insert into report_comment_answer (comment_id, reporter_id, reason, timestamp) values (5, 1, 'sit amet sem fusce consequat nulla nisl nunc nisl', '2022-11-02 17:41:25');
insert into report_comment_answer (comment_id, reporter_id, reason, timestamp) values (5, 11, 'ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit', '2023-01-02 04:40:05');

insert into user_vote_question (user_id, question_id, vote) values (1, 7, 1);
insert into user_vote_question (user_id, question_id, vote) values (5, 7, -1);
insert into user_vote_question (user_id, question_id, vote) values (13, 10, 1);
insert into user_vote_question (user_id, question_id, vote) values (9, 9, 1);
insert into user_vote_question (user_id, question_id, vote) values (12, 8, -1);
insert into user_vote_question (user_id, question_id, vote) values (6, 7, 1);
insert into user_vote_question (user_id, question_id, vote) values (1, 9, 1);
insert into user_vote_question (user_id, question_id, vote) values (18, 4, -1);
insert into user_vote_question (user_id, question_id, vote) values (11, 1, 1);
insert into user_vote_question (user_id, question_id, vote) values (20, 1, 1);
insert into user_vote_question (user_id, question_id, vote) values (14, 8, -1);
insert into user_vote_question (user_id, question_id, vote) values (8, 10, 1);
insert into user_vote_question (user_id, question_id, vote) values (10, 4, 1);
insert into user_vote_question (user_id, question_id, vote) values (5, 3, -1);
insert into user_vote_question (user_id, question_id, vote) values (13, 6, 1);

insert into user_vote_answer (user_id, answer_id, vote) values (2, 10, -1);
insert into user_vote_answer (user_id, answer_id, vote) values (14, 5, 1);
insert into user_vote_answer (user_id, answer_id, vote) values (1, 2, 1);
insert into user_vote_answer (user_id, answer_id, vote) values (16, 10, 1);
insert into user_vote_answer (user_id, answer_id, vote) values (5, 7, -1);
insert into user_vote_answer (user_id, answer_id, vote) values (7, 1, 1);
insert into user_vote_answer (user_id, answer_id, vote) values (7, 8, 1);
insert into user_vote_answer (user_id, answer_id, vote) values (15, 5, -1);
insert into user_vote_answer (user_id, answer_id, vote) values (19, 8, -1);
insert into user_vote_answer (user_id, answer_id, vote) values (7, 6, 1);
insert into user_vote_answer (user_id, answer_id, vote) values (17, 3, 1);
insert into user_vote_answer (user_id, answer_id, vote) values (6, 2, 1);
insert into user_vote_answer (user_id, answer_id, vote) values (13, 9, 1);
insert into user_vote_answer (user_id, answer_id, vote) values (17, 2, -1);
insert into user_vote_answer (user_id, answer_id, vote) values (19, 10, 1);

insert into user_vote_comment_question (user_id, comment_id, vote) values (10, 6, 1);
insert into user_vote_comment_question (user_id, comment_id, vote) values (18, 8, 1);
insert into user_vote_comment_question (user_id, comment_id, vote) values (8, 9, -1);
insert into user_vote_comment_question (user_id, comment_id, vote) values (13, 9, 1);
insert into user_vote_comment_question (user_id, comment_id, vote) values (5, 3, 1);
insert into user_vote_comment_question (user_id, comment_id, vote) values (3, 8, -1);
insert into user_vote_comment_question (user_id, comment_id, vote) values (20, 8, 1);
insert into user_vote_comment_question (user_id, comment_id, vote) values (18, 3, 1);
insert into user_vote_comment_question (user_id, comment_id, vote) values (10, 5, -1);
insert into user_vote_comment_question (user_id, comment_id, vote) values (20, 3, -1);
insert into user_vote_comment_question (user_id, comment_id, vote) values (14, 4, 1);
insert into user_vote_comment_question (user_id, comment_id, vote) values (6, 1, 1);
insert into user_vote_comment_question (user_id, comment_id, vote) values (14, 3, -1);
insert into user_vote_comment_question (user_id, comment_id, vote) values (13, 5, 1);
insert into user_vote_comment_question (user_id, comment_id, vote) values (3, 9, -1);

insert into user_vote_comment_answer (user_id, comment_id, vote) values (16, 2, 1);
insert into user_vote_comment_answer (user_id, comment_id, vote) values (3, 4, -1);
insert into user_vote_comment_answer (user_id, comment_id, vote) values (16, 8, 1);
insert into user_vote_comment_answer (user_id, comment_id, vote) values (17, 2, -1);
insert into user_vote_comment_answer (user_id, comment_id, vote) values (8, 3, 1);
insert into user_vote_comment_answer (user_id, comment_id, vote) values (16, 10, -1);
insert into user_vote_comment_answer (user_id, comment_id, vote) values (2, 4, 1);
insert into user_vote_comment_answer (user_id, comment_id, vote) values (13, 2, -1);
insert into user_vote_comment_answer (user_id, comment_id, vote) values (13, 10, 1);
insert into user_vote_comment_answer (user_id, comment_id, vote) values (12, 9, 1);
insert into user_vote_comment_answer (user_id, comment_id, vote) values (11, 3, 1);
insert into user_vote_comment_answer (user_id, comment_id, vote) values (4, 8, -1);
insert into user_vote_comment_answer (user_id, comment_id, vote) values (3, 2, -1);
insert into user_vote_comment_answer (user_id, comment_id, vote) values (7, 3, -1);
insert into user_vote_comment_answer (user_id, comment_id, vote) values (13, 3, 1);

insert into notification (content, date, TYPE, user_id) values ('volutpat eleifend donec ut dolor morbi', '2023-04-16 18:20:43', 'Question', 18);
insert into notification (content, date, TYPE, user_id) values ('ultrices libero non mattis pulvinar nulla pede', '2023-09-24 11:31:10', 'Comment', 10);
insert into notification (content, date, TYPE, user_id) values ('eleifend quam a odio in', '2023-04-02 15:59:47', 'Question', 11);
insert into notification (content, date, TYPE, user_id) values ('sagittis nam congue risus semper porta', '2023-07-13 00:22:43', 'Answer', 2);
insert into notification (content, date, TYPE, user_id) values ('condimentum id luctus nec molestie', '2023-10-01 15:12:33', 'Question', 1);
insert into notification (content, date, TYPE, user_id) values ('rhoncus sed vestibulum sit amet cursus id turpis', '2023-06-05 11:36:02', 'Answer', 14);
insert into notification (content, date, TYPE, user_id) values ('nisi nam ultrices libero non mattis pulvinar', '2023-10-11 17:03:32', 'Rating', 4);
insert into notification (content, date, TYPE, user_id) values ('justo morbi ut odio cras', '2023-05-12 20:34:24', 'Badge', 8);
insert into notification (content, date, TYPE, user_id) values ('nisi vulputate nonummy maecenas tincidunt lacus', '2023-03-11 11:23:46', 'Question', 9);
insert into notification (content, date, TYPE, user_id) values ('tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida', '2023-01-17 21:53:38', 'Comment', 17);
insert into notification (content, date, TYPE, user_id) values ('integer ac neque duis bibendum morbi', '2023-05-09 22:47:02', 'Question', 5);
insert into notification (content, date, TYPE, user_id) values ('aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas', '2023-05-24 08:11:59', 'Rating', 10);
insert into notification (content, date, TYPE, user_id) values ('velit donec diam neque vestibulum eget vulputate', '2023-05-20 08:37:09', 'Answer', 4);
insert into notification (content, date, TYPE, user_id) values ('suspendisse potenti cras in purus eu magna vulputate luctus cum', '2023-03-18 11:03:39', 'Rating', 5);
insert into notification (content, date, TYPE, user_id) values ('duis bibendum felis sed interdum venenatis turpis enim blandit mi', '2023-09-09 15:17:44', 'Badge', 15);
insert into notification (content, date, TYPE, user_id) values ('sagittis nam congue risus semper porta volutpat quam', '2023-10-12 00:01:10', 'Answer', 18);
insert into notification (content, date, TYPE, user_id) values ('pulvinar lobortis est phasellus sit', '2023-09-04 22:40:49', 'Question', 14);
insert into notification (content, date, TYPE, user_id) values ('in lacus curabitur at ipsum ac', '2023-05-02 05:31:46', 'Answer', 8);
insert into notification (content, date, TYPE, user_id) values ('turpis eget elit sodales scelerisque mauris', '2023-01-02 00:57:49', 'Comment', 4);
insert into notification (content, date, TYPE, user_id) values ('non lectus aliquam sit amet diam in magna bibendum', '2023-08-29 11:02:56', 'Question', 3);